CREATE TABLE IF NOT EXISTS tags (
  tag_id      SERIAL PRIMARY KEY,
  data        VARCHAR(200) NOT NULL UNIQUE,
  updated_at  DATETIME NOT NULL,
  created_at  DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
